version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume-challenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5d7yexaes2fz"
s3_prefix = "cloud-resume-challenge"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
